server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

# 👇 This is the missing part
clients:
  - url: http://192.168.40.156:3100/loki/api/v1/push

scrape_configs:
  - job_name: laravel
    static_configs:
      - targets: [localhost]
        labels:
          job: laravel-acms
          app: acms
          service_name: laravel
          __path__: /var/log/laravel/laravel.log

  - job_name: haproxy
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: .*hap.*   # only keep haproxy container
        action: keep
      # - source_labels: ['__meta_docker_container_name']
      #   target_label: container
      - replacement: haproxy
        target_label: service_name
      - replacement: haproxy-acms
        target_label: job
      - replacement: acms
        target_label: app
    # static_configs:
    #   - targets: [localhost]
    #     labels:
    #       job: haproxy
    #       app: acms
    #       __path__: /var/log/haproxy/*.log

  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:3500   # 👈 Promtail will listen for TCP logs here
      idle_timeout: 60s
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: 'host'
      - source_labels: ['__syslog_message_app_name']
        target_label: 'app'