name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # Navigate to your project directory
            cd /home/ubuntu/remycl  # Change this to your actual path
            
            # Pull latest code from GitHub
            git pull origin main
            
            # Rebuild Docker containers
            docker-compose down --remove-orphans
            docker rm -f $(docker ps -aq) 2>/dev/null || true
            docker-compose up -d --build
            
            # Run Laravel migrations and cache
            docker-compose exec -T php php artisan migrate --force 2>&1 || echo "Migration skipped"
            docker-compose exec -T php php artisan optimize:clear 2>&1 || echo "Cache clear skipped"
            #docker-compose exec -T php php artisan config:clear
            #docker-compose exec -T php php artisan route:clear
            #docker-compose exec -T php php artisan view:clear
