name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # Navigate to your project directory
            cd /home/ubuntu/remycl  # Change this to your actual path
            
            # Pull latest code from GitHub
            git pull origin main
            
            # Rebuild Docker containers
            docker-compose down --remove-orphans
            docker rm -f $(docker ps -aq) 2>/dev/null || true
            docker-compose up -d --build
            
            # Run Laravel migrations and cache
            docker-compose exec -T remycl_php php artisan migrate --force
            docker-compose exec -T remycl_php php artisan config:cache
            docker-compose exec -T remycl_php php artisan route:cache
            docker-compose exec -T remycl_php php artisan view:cache
